--- zlib/win32/Makefile.gcc	2012-05-02 20:17:58.000000000 +0200
+++ zlib/win32/Makefile.gcc	2013-04-13 00:16:50.286897167 +0200
@@ -36,12 +36,12 @@
 #
 # Set to 1 if shared object needs to be installed
 #
-SHARED_MODE=0
+SHARED_MODE=1
 
 #LOC = -DASMV
 #LOC = -DDEBUG -g
 
-PREFIX =
+PREFIX = i686-pc-mingw32-
 CC = $(PREFIX)gcc
 CFLAGS = $(LOC) -O3 -Wall
 
